### ISSUE TITLE
Scrambled: version webGL

### ISSUE THREAD

**Issue by cambridgekids** [cambridgekids/David-games#12]
Pásame please el Scrambled a una versión webGL para que pueda probar en las pizarras digitales de un colegio. Ellos tienen linux por lo tanto usaré el navegador.

**Comment by Deivith** [comment]
Here you go!:

http://cambridgekids.es/games/scrambled/

**Comment by cambridgekids** [comment]
Wow! OMG! No sabía que era así da fácil. En starling AIR es un coñazo.
1) Todo funciona pero no hay sonido.

He estado de ventas toda esta semana y me toca la semana que viene. Hay mucho interés y voy haciendo acuerdos. Te contaré más cuando hay un hueco tranquilo. Tengo que prestar muchísima atención a Unity a partir de ahora. Supongo que será ya la hora de mirar el engine. A ver si tengo la cabez lúcida mañana y si no el fin de semana. Estoy muy contento.

**Comment by Deivith** [comment]
Y me demore porque no tenia la libreria instalada! tuve que hacer click para instalarla y esperar !!

A mi me funciono el sonido (en chrome/windows/pc). En que combinación probaste tu?

**Comment by cambridgekids** [comment]
No me funciona.
Mac - chrome

Mac - firefox - sí que funciona.

**Comment by Deivith** [comment]
Hola Gerry, acabo de probar en la oficina que tengo MacOsx Con Chrome y me funciono el audio! es raro!

**Comment by Deivith** [comment]
No tienes otra mac para probar por las dudas?

**Comment by cambridgekids** [comment]
Estoy en el tres. Ahora mismo he actualizado chrome y ahora FUNCIONA bien. Yo pensaba que chrome se actualizaba sólo. Esto es bueno saberlo para que cuando un colegio se queje de esto en el futuro. Les diré update o cambia a firefox.

**Comment by cambridgekids** [comment]
Estas cosas joden pero vienen bien.

**Comment by Deivith** [comment]
Igual nunca lo actualice, siempre me anduvo eh!

**Comment by Deivith** [comment]
Ahhh tuviste que actualizar la version de chrome, ahora entiendo!!

**Comment by cambridgekids** [comment]
Yes
https://www.dropbox.com/s/5na5w1kjrdyhyis/Screenshot%202018-06-07%2021.00.17.png?dl=0
