### ISSUE TITLE
Crossword: Teclado en PC

### ISSUE THREAD

**Issue by cambridgekids** [cambridgekids/David-games#15]
1. Necesito que "user input" sea el teclado del PC tb y no sólo la opción del teclado virtual.
2. Al teclear una palabra a veces ya tiene una letra puesta ya que las palabras se crucen.
    Al teclear la palabra se salta la letra que ya está pero prefiero que lo "acepte" ya que es más natural para mi o para estudiantes de teclear la palabra entera y no saltar una letra si está.
Puedes observar Vocabulary Course (VB) de Starling.
3. Al apretar la primera letra de una palabra se tiene que dar prioridad a esa palabra aunque sea vertical.
    ej: Si aprietas C de CAT - se pone prioridad a DUCK pero obviamente si estoy apretando la C de Cat es porque quiero hacer esa palabra. Si fuera DUCK hubiera apretado la D osea la primera letra.

**Comment by Deivith** [comment]
@cambridgekids solucionado los items #1 y #3. Sin embargo tengo una duda respecto al item #2.

Estuve controlando la app original y pude detectar el funcionamiento que mencionas, sin embargo me surgieron algunas dudas al respecto. En el siguiente screenshot de la App original pude comprobar el siguiente funcionamiento:

![d7e2018a-8572-4dfe-984c-307d1ab3eb81](https://user-images.githubusercontent.com/2422479/44215566-39d8e380-a149-11e8-860e-133ef43142d3.jpeg)

Tengo las letras P, I S bloqueadas (por usar el Reveal).

- Si yo escribo SUR, al momento de llegar a la P, si aprieto la P genera una animacion sobre la letra P (la agranda), sin embargo si aprieto cualquier otra letra que no sea la P, me escribe la siguiente letra. 

Esto es el funcionamiento que mencionas arriba. Esta ok asi? Es decir no salteo la letra solamente si la letra que se ingresa es la misma que la bloqueada?

- El problema se presenta cuando sigo escribiendo y tengo bloqueadas 2 letras mas en este caso la letra I  y la letra S.  Cuando yo llegue a escribir la R, luego de eso si yo aprieto S, entonces me hace la animacion de la S (correcto), pero si aprieto la I o cualquier otra letra que no sea la S sigue escribiendo. Es decir, siempre toma como referencia la ultima letra bloqueada que encontro. Esta bien esto? Lo replico exactamente asi?

**Comment by cambridgekids** [comment]
Yo lo veo. Pues sí, si lo ves bien, replicalo. Un niño que tiene demasiadas letras reveladas va a volver a hacer el crossword y lo hará mejor escribiendo la mayoría de las palabras de una vez y con muy poco revelado, o sea mucho más natural.

**Comment by Deivith** [comment]
Fixed.
Fix will be deployed in next build.
