### ISSUE TITLE
Crossword: The erase button

### ISSUE THREAD

**Issue by cambridgekids** [cambridgekids/David-games#17]
The erase button (última tecla abajo derecha)
Tiene que ir "deleting" all the letras puestas si sigo apretando y no sólo la letra donde está.
Ej: Escribo DIP en vez de DOG. Y estoy en la letra P. Aprieto "erase button" y quiero "erase" P y I pero sólo me deja la P. Si quiero erase la I tengo que ponerme encima.
Es muy común ver a estudiantes "erasing" palabras enteras.

**Comment by Deivith** [comment]
Fixed.
Fix will be deployed in next build.
