### ISSUE TITLE
Crossword: Version webGL

### ISSUE THREAD

**Issue by cambridgekids** [cambridgekids/David-games#18]
De momento me funciona muy bien si dejo la pantalla en "normal screen" ie: not full screen.
PERO en full screen mode
1. Las palabras más abajo del todo: No se puede ver la últimas letras entonces si estás escribiendo o haces un error no las puedes ver.
2. Al apretar fuera o sea para que todo el crucigrama vuelva al centro - no se centraliza. Se queda desplazado abajo izquierda.
Este último no es tan imortante pero queda feo. Lo digo porque si me dices que es algo que desconoces pues lo podemos meter en los foros.

**Comment by Deivith** [comment]
Fixed.
Fix will be deployed in next build.
