### ISSUE TITLE
Crossword: Version webGL

### ISSUE THREAD

**Issue by cambridgekids** [cambridgekids/David-games#19]
Cuando entro con mi movil no se ve muy bien. Si observas el enlace de abajo.
Quizás sea porque moviles y tablets no son adecuados para utilizar esta tecnología online y son más para tener la app instalado. ¿Es así?

https://drive.google.com/open?id=1CElPwVbe5lKYCqMsCTOpkkGL4jFYl_YQ

**Comment by Deivith** [comment]
Claro, el webgl no es responsive. Si bien funciona porque acepta la funcionalidad, no se puede garantizar que funcione bien. Quizas se pueda modificar la misma pagina web (no el webgl) para que adapte el canvas a las resoluciones mobile, sin embargo no se podria controlar el tamanio de los elementos dentros del cambio. 

Lo ideal seria para mobiles es la App instalada. y para PC la version webgl.
