### ISSUE TITLE
PlayerPrefs are not available on multiple devices.

### ISSUE THREAD

**Issue by cambridgekids** [cambridgekids/David-games#2]
PlayerPrefs are used instead of shared objects. 
Problem: They are stored on the device ie: If the usser changes device his PlayerPrefs are not available.
ie: Instead of using his samsung tablet he decides to usse his samsung phone to play.

**Comment by Deivith** [comment]
@cambridgekids Claro, playerprefs sirve para guardar la data previa a la sync con un servidor.

**Comment by cambridgekids** [comment]
Excellent.
