### ISSUE TITLE
Crossword: Points/ Timer

### ISSUE THREAD

**Issue by cambridgekids** [cambridgekids/David-games#20]
El juego original tenía un algoritmo sencillo basado en el tiempo pasado + penalidades si usabas revelar letra etc... y se traducía a puntos. No quiero usar ese sistema.
Prefiero que sea de tiempo y punto. De o para arriba hasta el infinito. Luego veremos cuantas estrellas adjudicamos según el tiempo pasado. Y se quita 1 corazón.
1. Se añade una penalidad de 10 segundos por cada letra revelada. Y se quita un corazon.
2. Se añade una penalidad de 30 segundos por cada vez que usan el panel de pistas lateral. Eso es porque lo usan mucho. Y se quitan dos corazones. Uno con ruido y después otro para que quede bien claro que se les haya quitado dos corazones.
Luego (ahora no) haremos una liga y el primero estára el de menos tiempo obviamente. 
Esta es una manera muy clara de ver que tal lo han hecho. Con puntos los niños no entendían porque tenía 850 puntos o 1050 puntos.
3. Cada vez que haya penalización que se oiga o vea para que los niños sepan que hayan sido penalizados.

**Comment by Deivith** [comment]
Ok, lo implemento ahora que es bien facil eso (de hecho ya se estan ejecutando los sonidos de error y se quitan corazones). Me pongo a agregar tiempo por penalizacion y lo muestro.

Por ahora dejo las estrellas y los "puntos" ganados, hasta que veamos como lo resolvemos y de ser necesario cambiamos la pantalla de Game Over, te parece?

**Comment by cambridgekids** [comment]
Me parece perfecto.

**Comment by Deivith** [comment]
Added.
Fix will be deployed in next build.
