### ISSUE TITLE
Crossword: webGL - Bug

### ISSUE THREAD

**Issue by cambridgekids** [cambridgekids/David-games#22]
Voy a intentar reproducir este bug. Pone FIHH (FISH) como bien.
Ya - Pongo HORSE y luego PIG. Entonces clickeo en la primera letra F y tecleo con el teclado FISH.
Aparece FIHH y le pone como bien.
Más feedback.
Tecleas lento y sale FISH
Tecleas rápido y sale FIHH
Me parece que tiene que ver con al der rápido no puede con la animación y el input que esté recibiendo.

https://drive.google.com/open?id=10zfqYkUxJPxskXVI27yHdyWg11XCPxbR

**Comment by Deivith** [comment]
@cambridgekids Fixed. Que buen bug que encontraste!!

Tambien se sumo la actualizacion que permite que se pueda poner full screen por mas que tengas algo seleccionado en el tablero.
